name: Azure Static Web Apps CI/CD

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: true
        type: string
      type-project:
        description: "Tracker or Sigpro"
        required: true
        type: string
      output-location:
        description: "Output location"
        required: true
        type: string
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ""
          app_location: "/"
          api_location: ""
          output_location: ${{ inputs.output-location }}
          deployment_action: "upload"
